stages:
  - test

test:
  stage: test
  image: python:3.7
  before_script:
    - pip install 'setuptools<46.0.0'
    - pip install -r $CI_PROJECT_DIR/requirements.txt
    - pip install -e $CI_PROJECT_DIR
    - python -c "import secrets; print(f'SECRET_KEY = \"{secrets.token_hex(16)}\"')" > $CI_PROJECT_DIR/datamadsite/settings_local.py
  script:
    - python manage.py test datamad2.tests