# Generated by Django 4.2 on 2025-02-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0013_auto_20240704_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedgrant',
            name='UKRI_ref',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
