# Generated by Django 4.2 on 2025-02-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0014_importedgrant_ukri_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importedgrant',
            old_name='UKRI_ref',
            new_name='nerc_id',
        ),
    ]
