# Generated by Django 4.2 on 2025-02-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0015_rename_ukri_ref_importedgrant_nerc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedgrant',
            name='ukri_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
