# Generated by Django 4.2 on 2025-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0016_importedgrant_ukri_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissuetype',
            name='nerc_id_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='NERC ID Field ID'),
        ),
    ]
