# Generated by Django 4.2 on 2025-08-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0017_jiraissuetype_nerc_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='facility',
            field=models.TextField(blank=True, default=''),
        ),
    ]
