# Generated by Django 4.2 on 2025-08-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0018_alter_importedgrant_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='routing_classification',
            field=models.CharField(blank=True, choices=[('Marine', 'Marine'), ('Earth', 'Earth'), ('Atmospheric', 'Atmospheric'), ('Freshwater', 'Freshwater'), ('Terrestrial', 'Terrestrial'), ('Earth Observation', 'Earth Observation'), ('Panel A', 'Panel A'), ('Panel B', 'Panel B'), ('Panel C', 'Panel C'), ('BODC', 'BODC'), ('CEDA', 'CEDA'), ('EIDC', 'EIDC'), ('NGDC', 'NGDC'), ('PDC', 'PDC')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='secondary_classification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
