# Generated by Django 4.2 on 2025-09-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0019_alter_importedgrant_routing_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedgrant',
            name='data_management',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='secondary_classification',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
