# Generated by Django 4.2 on 2026-09-02 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0020_importedgrant_data_management_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subtask',
            new_name='JIRASubtask',
        ),
        migrations.AddField(
            model_name='datacentre',
            name='github_project',
            field=models.CharField(blank=True, max_length=100, verbose_name='Data Management Github Project'),
        ),
        migrations.CreateModel(
            name='GithubTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('datacentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamad2.datacentre')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamad2.grant')),
            ],
        ),
        migrations.CreateModel(
            name='GithubSubtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('schedule_time', models.IntegerField(blank=True, help_text='Time in weeks to at which to schedule sub-task in reference to the reference time. Using a negative value schedules the task before the reference time', null=True, verbose_name='Schedule at')),
                ('ref_time', models.CharField(blank=True, choices=[('start_date', 'Start Date'), ('end_date', 'End Date')], help_text='Start date means the sub-task will be scheduled in reference to the start date. End date means it will be scheduled in reference to the end date.', max_length=200, null=True, verbose_name='Reference time')),
                ('data_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datamad2.datacentre')),
            ],
        ),
        migrations.CreateModel(
            name='GithubIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuetype', models.IntegerField(blank=True, help_text='Github Data Management issue type ID. e.g. 10602', null=True, verbose_name='Issue Type Id')),
                ('start_date_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Actual Start Date Field ID')),
                ('end_date_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Actual End Date Field ID')),
                ('proposed_start_date_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Proposed Start Date Field ID')),
                ('proposed_end_date_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Proposed End Date Field ID')),
                ('grant_ref_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Grant Ref Field ID')),
                ('nerc_id_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='NERC ID Field ID')),
                ('pi_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Principle Investigator Field ID')),
                ('research_org_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Research Org Field ID')),
                ('primary_datacentre_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Primary Datacentre Field ID')),
                ('amount_awarded_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Amount Awarded Field ID')),
                ('grant_type_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Grant Type Field ID')),
                ('lead_grant_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Lead Grant Field ID')),
                ('parent_grant_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Parent Grant Field ID')),
                ('child_grants_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Child Grants Field ID')),
                ('email_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Email Field ID')),
                ('work_number_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Work Number Field ID')),
                ('alt_data_contact_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Alt Data Contact Field ID')),
                ('alt_data_contact_email_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Alt Data Contact Email Field ID')),
                ('other_datacentre_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Other Datacentre Field ID')),
                ('call_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Call Field ID')),
                ('scheme_field', models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Scheme Field ID')),
                ('datacentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamad2.datacentre')),
                ('reporter', models.ForeignKey(blank=True, help_text='User to set as the reporter for all Github issues. If left blank the reporter will be the user that creates the issue.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
