# Generated by Django 4.2 on 2026-09-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0021_rename_subtask_jirasubtask_datacentre_github_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubissuetype',
            name='issuetype',
        ),
        migrations.AddField(
            model_name='githubissuetype',
            name='project_name',
            field=models.CharField(blank=True, help_text='Github Data Management project name, e.g. " CEDA NERC Data Management (default)"', max_length=100, null=True, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='alt_data_contact_email_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Alt Data Contact Email) | Returned DataType: String', max_length=50, verbose_name='Alt Data Contact Email Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='alt_data_contact_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Alt Data Contact) | Returned DataType: String', max_length=50, verbose_name='Alt Data Contact Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='amount_awarded_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Amount Awarded) | Returned DataType: String', max_length=50, verbose_name='Amount Awarded Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='call_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Call) | Returned DataType: String', max_length=50, verbose_name='Call Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='child_grants_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Child Grants) | Returned DataType: String', max_length=50, verbose_name='Child Grants Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='email_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Email) | Returned DataType: String', max_length=50, verbose_name='Email Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='end_date_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. End Date) | Returned DataType: String', max_length=100, verbose_name='Actual End Date Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='grant_ref_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Grant Reference) | Returned DataType: String', max_length=100, verbose_name='Grant Ref Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='grant_type_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Grant Type) | Returned DataType: String', max_length=50, verbose_name='Grant Type Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='lead_grant_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Lead Grant) | Returned DataType: String', max_length=50, verbose_name='Lead Grant Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='nerc_id_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. NERC ID) | Returned DataType: String', max_length=100, verbose_name='NERC ID Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='other_datacentre_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Other Datacentre) | Returned DataType: String', max_length=50, verbose_name='Other Datacentre Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='parent_grant_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Parent Grant) | Returned DataType: String', max_length=50, verbose_name='Parent Grant Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='pi_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. PI) | Returned DataType: String', max_length=100, verbose_name='Principle Investigator Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='primary_datacentre_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Primary Datacentre) | Returned DataType: String', max_length=100, verbose_name='Primary Datacentre Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='proposed_end_date_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Proposed End Date) | Returned DataType: String', max_length=50, verbose_name='Proposed End Date Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='proposed_start_date_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Proposed Start Date) | Returned DataType: String', max_length=50, verbose_name='Proposed Start Date Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='research_org_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Research Organisation) | Returned DataType: String', max_length=100, verbose_name='Research Org Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='scheme_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Scheme) | Returned DataType: String', max_length=50, verbose_name='Scheme Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='start_date_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Start Date) | Returned DataType: String', max_length=100, verbose_name='Actual Start Date Field ID'),
        ),
        migrations.AlterField(
            model_name='githubissuetype',
            name='work_number_field',
            field=models.CharField(blank=True, help_text='Format: name of Github issue type (e.g. Work Number) | Returned DataType: String', max_length=50, verbose_name='Work Number Field ID'),
        ),
    ]
