# Generated by Django 5.2.17 on 2026-09-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0022_remove_githubissuetype_issuetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Github Username'),
        ),
    ]
